name: golangci-lint
on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.26']
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Download module dependencies
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
